//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Seagate.AAS.HGA.HST.SeagateDataBaseLogIn {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AuthenticationOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CollectUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUserExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchStaffOperationCompleted;
        
        private System.Threading.SendOrPostCallback CollectStaffOperationCompleted;
        
        private System.Threading.SendOrPostCallback CollectRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUnavailableUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckEmployeeAvailableOperationCompleted;
        
        private System.Threading.SendOrPostCallback CollectMachinePasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Seagate.AAS.HGA.HST.Properties.Settings.Default.HST_meapps_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthenticationCompletedEventHandler AuthenticationCompleted;
        
        /// <remarks/>
        public event InitializeCompletedEventHandler InitializeCompleted;
        
        /// <remarks/>
        public event AuthenticateCompletedEventHandler AuthenticateCompleted;
        
        /// <remarks/>
        public event CollectUserInfoCompletedEventHandler CollectUserInfoCompleted;
        
        /// <remarks/>
        public event IsUserExistCompletedEventHandler IsUserExistCompleted;
        
        /// <remarks/>
        public event SearchStaffCompletedEventHandler SearchStaffCompleted;
        
        /// <remarks/>
        public event CollectStaffCompletedEventHandler CollectStaffCompleted;
        
        /// <remarks/>
        public event CollectRoleCompletedEventHandler CollectRoleCompleted;
        
        /// <remarks/>
        public event WriteUserInfoCompletedEventHandler WriteUserInfoCompleted;
        
        /// <remarks/>
        public event DeleteUnavailableUserCompletedEventHandler DeleteUnavailableUserCompleted;
        
        /// <remarks/>
        public event UpdateUserRoleCompletedEventHandler UpdateUserRoleCompleted;
        
        /// <remarks/>
        public event CheckEmployeeAvailableCompletedEventHandler CheckEmployeeAvailableCompleted;
        
        /// <remarks/>
        public event CollectMachinePasswordCompletedEventHandler CollectMachinePasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Authentication", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserInfo Authentication(string mySeagateId, string mySeagatePassword, string MachineType) {
            object[] results = this.Invoke("Authentication", new object[] {
                        mySeagateId,
                        mySeagatePassword,
                        MachineType});
            return ((UserInfo)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticationAsync(string mySeagateId, string mySeagatePassword, string MachineType) {
            this.AuthenticationAsync(mySeagateId, mySeagatePassword, MachineType, null);
        }
        
        /// <remarks/>
        public void AuthenticationAsync(string mySeagateId, string mySeagatePassword, string MachineType, object userState) {
            if ((this.AuthenticationOperationCompleted == null)) {
                this.AuthenticationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticationOperationCompleted);
            }
            this.InvokeAsync("Authentication", new object[] {
                        mySeagateId,
                        mySeagatePassword,
                        MachineType}, this.AuthenticationOperationCompleted, userState);
        }
        
        private void OnAuthenticationOperationCompleted(object arg) {
            if ((this.AuthenticationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticationCompleted(this, new AuthenticationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Initialize", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InitStatus Initialize() {
            object[] results = this.Invoke("Initialize", new object[0]);
            return ((InitStatus)(results[0]));
        }
        
        /// <remarks/>
        public void InitializeAsync() {
            this.InitializeAsync(null);
        }
        
        /// <remarks/>
        public void InitializeAsync(object userState) {
            if ((this.InitializeOperationCompleted == null)) {
                this.InitializeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeOperationCompleted);
            }
            this.InvokeAsync("Initialize", new object[0], this.InitializeOperationCompleted, userState);
        }
        
        private void OnInitializeOperationCompleted(object arg) {
            if ((this.InitializeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeCompleted(this, new InitializeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Authenticate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginInfo Authenticate(LdapServer Server, string mySeagateId, string mySeagatePassword) {
            object[] results = this.Invoke("Authenticate", new object[] {
                        Server,
                        mySeagateId,
                        mySeagatePassword});
            return ((LoginInfo)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateAsync(LdapServer Server, string mySeagateId, string mySeagatePassword) {
            this.AuthenticateAsync(Server, mySeagateId, mySeagatePassword, null);
        }
        
        /// <remarks/>
        public void AuthenticateAsync(LdapServer Server, string mySeagateId, string mySeagatePassword, object userState) {
            if ((this.AuthenticateOperationCompleted == null)) {
                this.AuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateOperationCompleted);
            }
            this.InvokeAsync("Authenticate", new object[] {
                        Server,
                        mySeagateId,
                        mySeagatePassword}, this.AuthenticateOperationCompleted, userState);
        }
        
        private void OnAuthenticateOperationCompleted(object arg) {
            if ((this.AuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CollectUserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginInfo CollectUserInfo(string SoftwareAccessCode, LdapServer Server, string mySeagateId) {
            object[] results = this.Invoke("CollectUserInfo", new object[] {
                        SoftwareAccessCode,
                        Server,
                        mySeagateId});
            return ((LoginInfo)(results[0]));
        }
        
        /// <remarks/>
        public void CollectUserInfoAsync(string SoftwareAccessCode, LdapServer Server, string mySeagateId) {
            this.CollectUserInfoAsync(SoftwareAccessCode, Server, mySeagateId, null);
        }
        
        /// <remarks/>
        public void CollectUserInfoAsync(string SoftwareAccessCode, LdapServer Server, string mySeagateId, object userState) {
            if ((this.CollectUserInfoOperationCompleted == null)) {
                this.CollectUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCollectUserInfoOperationCompleted);
            }
            this.InvokeAsync("CollectUserInfo", new object[] {
                        SoftwareAccessCode,
                        Server,
                        mySeagateId}, this.CollectUserInfoOperationCompleted, userState);
        }
        
        private void OnCollectUserInfoOperationCompleted(object arg) {
            if ((this.CollectUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CollectUserInfoCompleted(this, new CollectUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsUserExist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsUserExist(string mySeagateId) {
            object[] results = this.Invoke("IsUserExist", new object[] {
                        mySeagateId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUserExistAsync(string mySeagateId) {
            this.IsUserExistAsync(mySeagateId, null);
        }
        
        /// <remarks/>
        public void IsUserExistAsync(string mySeagateId, object userState) {
            if ((this.IsUserExistOperationCompleted == null)) {
                this.IsUserExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUserExistOperationCompleted);
            }
            this.InvokeAsync("IsUserExist", new object[] {
                        mySeagateId}, this.IsUserExistOperationCompleted, userState);
        }
        
        private void OnIsUserExistOperationCompleted(object arg) {
            if ((this.IsUserExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUserExistCompleted(this, new IsUserExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchStaff", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StaffInfo SearchStaff(string SoftwareAccessCode, StaffSearchParam SearchParam, string SearchPattern) {
            object[] results = this.Invoke("SearchStaff", new object[] {
                        SoftwareAccessCode,
                        SearchParam,
                        SearchPattern});
            return ((StaffInfo)(results[0]));
        }
        
        /// <remarks/>
        public void SearchStaffAsync(string SoftwareAccessCode, StaffSearchParam SearchParam, string SearchPattern) {
            this.SearchStaffAsync(SoftwareAccessCode, SearchParam, SearchPattern, null);
        }
        
        /// <remarks/>
        public void SearchStaffAsync(string SoftwareAccessCode, StaffSearchParam SearchParam, string SearchPattern, object userState) {
            if ((this.SearchStaffOperationCompleted == null)) {
                this.SearchStaffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchStaffOperationCompleted);
            }
            this.InvokeAsync("SearchStaff", new object[] {
                        SoftwareAccessCode,
                        SearchParam,
                        SearchPattern}, this.SearchStaffOperationCompleted, userState);
        }
        
        private void OnSearchStaffOperationCompleted(object arg) {
            if ((this.SearchStaffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchStaffCompleted(this, new SearchStaffCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CollectStaff", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StaffInfo CollectStaff(string SoftwareAccessCode) {
            object[] results = this.Invoke("CollectStaff", new object[] {
                        SoftwareAccessCode});
            return ((StaffInfo)(results[0]));
        }
        
        /// <remarks/>
        public void CollectStaffAsync(string SoftwareAccessCode) {
            this.CollectStaffAsync(SoftwareAccessCode, null);
        }
        
        /// <remarks/>
        public void CollectStaffAsync(string SoftwareAccessCode, object userState) {
            if ((this.CollectStaffOperationCompleted == null)) {
                this.CollectStaffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCollectStaffOperationCompleted);
            }
            this.InvokeAsync("CollectStaff", new object[] {
                        SoftwareAccessCode}, this.CollectStaffOperationCompleted, userState);
        }
        
        private void OnCollectStaffOperationCompleted(object arg) {
            if ((this.CollectStaffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CollectStaffCompleted(this, new CollectStaffCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CollectRole", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RoleInfo CollectRole() {
            object[] results = this.Invoke("CollectRole", new object[0]);
            return ((RoleInfo)(results[0]));
        }
        
        /// <remarks/>
        public void CollectRoleAsync() {
            this.CollectRoleAsync(null);
        }
        
        /// <remarks/>
        public void CollectRoleAsync(object userState) {
            if ((this.CollectRoleOperationCompleted == null)) {
                this.CollectRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCollectRoleOperationCompleted);
            }
            this.InvokeAsync("CollectRole", new object[0], this.CollectRoleOperationCompleted, userState);
        }
        
        private void OnCollectRoleOperationCompleted(object arg) {
            if ((this.CollectRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CollectRoleCompleted(this, new CollectRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WriteUserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WriteStatus WriteUserInfo(string SoftwareAccessCode, LoginInfo UserInfo) {
            object[] results = this.Invoke("WriteUserInfo", new object[] {
                        SoftwareAccessCode,
                        UserInfo});
            return ((WriteStatus)(results[0]));
        }
        
        /// <remarks/>
        public void WriteUserInfoAsync(string SoftwareAccessCode, LoginInfo UserInfo) {
            this.WriteUserInfoAsync(SoftwareAccessCode, UserInfo, null);
        }
        
        /// <remarks/>
        public void WriteUserInfoAsync(string SoftwareAccessCode, LoginInfo UserInfo, object userState) {
            if ((this.WriteUserInfoOperationCompleted == null)) {
                this.WriteUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteUserInfoOperationCompleted);
            }
            this.InvokeAsync("WriteUserInfo", new object[] {
                        SoftwareAccessCode,
                        UserInfo}, this.WriteUserInfoOperationCompleted, userState);
        }
        
        private void OnWriteUserInfoOperationCompleted(object arg) {
            if ((this.WriteUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteUserInfoCompleted(this, new WriteUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteUnavailableUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WriteStatus DeleteUnavailableUser(string SoftwareAccessCode, string mySeagateId) {
            object[] results = this.Invoke("DeleteUnavailableUser", new object[] {
                        SoftwareAccessCode,
                        mySeagateId});
            return ((WriteStatus)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUnavailableUserAsync(string SoftwareAccessCode, string mySeagateId) {
            this.DeleteUnavailableUserAsync(SoftwareAccessCode, mySeagateId, null);
        }
        
        /// <remarks/>
        public void DeleteUnavailableUserAsync(string SoftwareAccessCode, string mySeagateId, object userState) {
            if ((this.DeleteUnavailableUserOperationCompleted == null)) {
                this.DeleteUnavailableUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUnavailableUserOperationCompleted);
            }
            this.InvokeAsync("DeleteUnavailableUser", new object[] {
                        SoftwareAccessCode,
                        mySeagateId}, this.DeleteUnavailableUserOperationCompleted, userState);
        }
        
        private void OnDeleteUnavailableUserOperationCompleted(object arg) {
            if ((this.DeleteUnavailableUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUnavailableUserCompleted(this, new DeleteUnavailableUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateUserRole", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WriteStatus UpdateUserRole(string SoftwareAccessCode, string mySeagateId, int Role) {
            object[] results = this.Invoke("UpdateUserRole", new object[] {
                        SoftwareAccessCode,
                        mySeagateId,
                        Role});
            return ((WriteStatus)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserRoleAsync(string SoftwareAccessCode, string mySeagateId, int Role) {
            this.UpdateUserRoleAsync(SoftwareAccessCode, mySeagateId, Role, null);
        }
        
        /// <remarks/>
        public void UpdateUserRoleAsync(string SoftwareAccessCode, string mySeagateId, int Role, object userState) {
            if ((this.UpdateUserRoleOperationCompleted == null)) {
                this.UpdateUserRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserRoleOperationCompleted);
            }
            this.InvokeAsync("UpdateUserRole", new object[] {
                        SoftwareAccessCode,
                        mySeagateId,
                        Role}, this.UpdateUserRoleOperationCompleted, userState);
        }
        
        private void OnUpdateUserRoleOperationCompleted(object arg) {
            if ((this.UpdateUserRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserRoleCompleted(this, new UpdateUserRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckEmployeeAvailable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckEmployeeAvailable(LdapServer Server, string mySeagateId) {
            object[] results = this.Invoke("CheckEmployeeAvailable", new object[] {
                        Server,
                        mySeagateId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckEmployeeAvailableAsync(LdapServer Server, string mySeagateId) {
            this.CheckEmployeeAvailableAsync(Server, mySeagateId, null);
        }
        
        /// <remarks/>
        public void CheckEmployeeAvailableAsync(LdapServer Server, string mySeagateId, object userState) {
            if ((this.CheckEmployeeAvailableOperationCompleted == null)) {
                this.CheckEmployeeAvailableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckEmployeeAvailableOperationCompleted);
            }
            this.InvokeAsync("CheckEmployeeAvailable", new object[] {
                        Server,
                        mySeagateId}, this.CheckEmployeeAvailableOperationCompleted, userState);
        }
        
        private void OnCheckEmployeeAvailableOperationCompleted(object arg) {
            if ((this.CheckEmployeeAvailableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckEmployeeAvailableCompleted(this, new CheckEmployeeAvailableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CollectMachinePassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MachinePassword CollectMachinePassword(string MachineUsers) {
            object[] results = this.Invoke("CollectMachinePassword", new object[] {
                        MachineUsers});
            return ((MachinePassword)(results[0]));
        }
        
        /// <remarks/>
        public void CollectMachinePasswordAsync(string MachineUsers) {
            this.CollectMachinePasswordAsync(MachineUsers, null);
        }
        
        /// <remarks/>
        public void CollectMachinePasswordAsync(string MachineUsers, object userState) {
            if ((this.CollectMachinePasswordOperationCompleted == null)) {
                this.CollectMachinePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCollectMachinePasswordOperationCompleted);
            }
            this.InvokeAsync("CollectMachinePassword", new object[] {
                        MachineUsers}, this.CollectMachinePasswordOperationCompleted, userState);
        }
        
        private void OnCollectMachinePasswordOperationCompleted(object arg) {
            if ((this.CollectMachinePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CollectMachinePasswordCompleted(this, new CollectMachinePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInfo {
        
        private string pLANTField;
        
        private string eMP_GIDField;
        
        private string eMP_NAMEField;
        
        private string eMP_EMAILField;
        
        private string mGR_IDField;
        
        private string mGR_NAMEField;
        
        private string mGR_EMAILField;
        
        private string jOB_TITLEField;
        
        private string dEPARTMENTField;
        
        private bool eN_STATUSField;
        
        private bool aCCESS_GRANTField;
        
        private int[] rOLE_GRANTField;
        
        private System.DateTime uPDATE_DATEField;
        
        private bool loginPassField;
        
        private string errDescField;
        
        /// <remarks/>
        public string PLANT {
            get {
                return this.pLANTField;
            }
            set {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        public string EMP_GID {
            get {
                return this.eMP_GIDField;
            }
            set {
                this.eMP_GIDField = value;
            }
        }
        
        /// <remarks/>
        public string EMP_NAME {
            get {
                return this.eMP_NAMEField;
            }
            set {
                this.eMP_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string EMP_EMAIL {
            get {
                return this.eMP_EMAILField;
            }
            set {
                this.eMP_EMAILField = value;
            }
        }
        
        /// <remarks/>
        public string MGR_ID {
            get {
                return this.mGR_IDField;
            }
            set {
                this.mGR_IDField = value;
            }
        }
        
        /// <remarks/>
        public string MGR_NAME {
            get {
                return this.mGR_NAMEField;
            }
            set {
                this.mGR_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string MGR_EMAIL {
            get {
                return this.mGR_EMAILField;
            }
            set {
                this.mGR_EMAILField = value;
            }
        }
        
        /// <remarks/>
        public string JOB_TITLE {
            get {
                return this.jOB_TITLEField;
            }
            set {
                this.jOB_TITLEField = value;
            }
        }
        
        /// <remarks/>
        public string DEPARTMENT {
            get {
                return this.dEPARTMENTField;
            }
            set {
                this.dEPARTMENTField = value;
            }
        }
        
        /// <remarks/>
        public bool EN_STATUS {
            get {
                return this.eN_STATUSField;
            }
            set {
                this.eN_STATUSField = value;
            }
        }
        
        /// <remarks/>
        public bool ACCESS_GRANT {
            get {
                return this.aCCESS_GRANTField;
            }
            set {
                this.aCCESS_GRANTField = value;
            }
        }
        
        /// <remarks/>
        public int[] ROLE_GRANT {
            get {
                return this.rOLE_GRANTField;
            }
            set {
                this.rOLE_GRANTField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UPDATE_DATE {
            get {
                return this.uPDATE_DATEField;
            }
            set {
                this.uPDATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public bool LoginPass {
            get {
                return this.loginPassField;
            }
            set {
                this.loginPassField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MachinePassword {
        
        private string[] passwordField;
        
        private bool isCompletedField;
        
        private string errDescField;
        
        /// <remarks/>
        public string[] Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCompleted {
            get {
                return this.isCompletedField;
            }
            set {
                this.isCompletedField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WriteStatus {
        
        private bool isCompletedField;
        
        private string errDescField;
        
        /// <remarks/>
        public bool IsCompleted {
            get {
                return this.isCompletedField;
            }
            set {
                this.isCompletedField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RoleInfo {
        
        private string[] textField;
        
        private int[] valueField;
        
        private bool isCompletedField;
        
        private string errDescField;
        
        /// <remarks/>
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public int[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCompleted {
            get {
                return this.isCompletedField;
            }
            set {
                this.isCompletedField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StaffInfo {
        
        private LoginInfo[] myStaffInfoField;
        
        private bool isCompletedField;
        
        private string errDescField;
        
        /// <remarks/>
        public LoginInfo[] MyStaffInfo {
            get {
                return this.myStaffInfoField;
            }
            set {
                this.myStaffInfoField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCompleted {
            get {
                return this.isCompletedField;
            }
            set {
                this.isCompletedField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginInfo {
        
        private string pLANTField;
        
        private string eMP_GIDField;
        
        private string eMP_NAMEField;
        
        private string eMP_EMAILField;
        
        private int gLOBAL_GRADEField;
        
        private string jOB_NAMEField;
        
        private string sUP_GIDField;
        
        private string sUP_NAMEField;
        
        private string hC_GRPField;
        
        private int rOLE_NOField;
        
        private string rOLEField;
        
        private System.DateTime uPDATE_DATEField;
        
        private bool loginOKField;
        
        private string errDescField;
        
        /// <remarks/>
        public string PLANT {
            get {
                return this.pLANTField;
            }
            set {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        public string EMP_GID {
            get {
                return this.eMP_GIDField;
            }
            set {
                this.eMP_GIDField = value;
            }
        }
        
        /// <remarks/>
        public string EMP_NAME {
            get {
                return this.eMP_NAMEField;
            }
            set {
                this.eMP_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string EMP_EMAIL {
            get {
                return this.eMP_EMAILField;
            }
            set {
                this.eMP_EMAILField = value;
            }
        }
        
        /// <remarks/>
        public int GLOBAL_GRADE {
            get {
                return this.gLOBAL_GRADEField;
            }
            set {
                this.gLOBAL_GRADEField = value;
            }
        }
        
        /// <remarks/>
        public string JOB_NAME {
            get {
                return this.jOB_NAMEField;
            }
            set {
                this.jOB_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string SUP_GID {
            get {
                return this.sUP_GIDField;
            }
            set {
                this.sUP_GIDField = value;
            }
        }
        
        /// <remarks/>
        public string SUP_NAME {
            get {
                return this.sUP_NAMEField;
            }
            set {
                this.sUP_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string HC_GRP {
            get {
                return this.hC_GRPField;
            }
            set {
                this.hC_GRPField = value;
            }
        }
        
        /// <remarks/>
        public int ROLE_NO {
            get {
                return this.rOLE_NOField;
            }
            set {
                this.rOLE_NOField = value;
            }
        }
        
        /// <remarks/>
        public string ROLE {
            get {
                return this.rOLEField;
            }
            set {
                this.rOLEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UPDATE_DATE {
            get {
                return this.uPDATE_DATEField;
            }
            set {
                this.uPDATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public bool LoginOK {
            get {
                return this.loginOKField;
            }
            set {
                this.loginOKField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InitStatus {
        
        private bool isCompletedField;
        
        private string errDescField;
        
        /// <remarks/>
        public bool IsCompleted {
            get {
                return this.isCompletedField;
            }
            set {
                this.isCompletedField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDesc {
            get {
                return this.errDescField;
            }
            set {
                this.errDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LdapServer {
        
        /// <remarks/>
        AMK,
        
        /// <remarks/>
        OKC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum StaffSearchParam {
        
        /// <remarks/>
        EMP_ID,
        
        /// <remarks/>
        EMP_NAME,
        
        /// <remarks/>
        SUP_ID,
        
        /// <remarks/>
        SUP_NAME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AuthenticationCompletedEventHandler(object sender, AuthenticationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void InitializeCompletedEventHandler(object sender, InitializeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitializeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitializeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InitStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InitStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AuthenticateCompletedEventHandler(object sender, AuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CollectUserInfoCompletedEventHandler(object sender, CollectUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CollectUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CollectUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void IsUserExistCompletedEventHandler(object sender, IsUserExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUserExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUserExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SearchStaffCompletedEventHandler(object sender, SearchStaffCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchStaffCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchStaffCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StaffInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StaffInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CollectStaffCompletedEventHandler(object sender, CollectStaffCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CollectStaffCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CollectStaffCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StaffInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StaffInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CollectRoleCompletedEventHandler(object sender, CollectRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CollectRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CollectRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RoleInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RoleInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void WriteUserInfoCompletedEventHandler(object sender, WriteUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WriteStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WriteStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void DeleteUnavailableUserCompletedEventHandler(object sender, DeleteUnavailableUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUnavailableUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUnavailableUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WriteStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WriteStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateUserRoleCompletedEventHandler(object sender, UpdateUserRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WriteStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WriteStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CheckEmployeeAvailableCompletedEventHandler(object sender, CheckEmployeeAvailableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckEmployeeAvailableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckEmployeeAvailableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CollectMachinePasswordCompletedEventHandler(object sender, CollectMachinePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CollectMachinePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CollectMachinePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MachinePassword Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MachinePassword)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591