//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Resources;
using System.Reflection;

// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Martin Granell, Readify
// 
//      It contains classes defined from the contents of the resource file:
//        C:\AAS_SDK\Assemblies\Seagate.AAS.Parsel\SR.resx
// 
//      Generated: Friday, September 16, 2005 3:54 PM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace Seagate.AAS.Parsel.Services
{
    
    
    internal class SR
    {
        
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return Keys.Culture;
            }
            set
            {
                Keys.Culture = value;
            }
        }
        
        internal static string DirectorySetup
        {
            get
            {
                return Keys.GetString(Keys.DirectorySetup);
            }
        }
        
        internal class Keys
        {
            
            static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager(typeof(SR));
            
            static System.Globalization.CultureInfo _culture = null;
            
            internal const string DirectorySetup = "DirectorySetup";
            
            internal static System.Globalization.CultureInfo Culture
            {
                get
                {
                    return _culture;
                }
                set
                {
                    _culture = value;
                }
            }
            
            internal static string GetString(string key)
            {
                return resourceManager.GetString(key, _culture);
            }
            
            internal static string GetString(string key, object[] args)
            {
                string msg = resourceManager.GetString(key, _culture);
                msg = string.Format(msg, args);
                return msg;
            }
        }
    }
}
