//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

namespace Seagate.AAS.Parsel.Device.RFID.Hga
{
	/// <summary>
	/// Summary description for FrmHgaRfidDialog.
	/// </summary>

	partial class BolaTagDataForm : System.Windows.Forms.Form
		{
		/// <summary>
		/// Required designer variable.
		/// </summary>
        private System.ComponentModel.Container components = null;





		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if (components != null) 
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

					#region DudeLabs LLC RCConverter generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.label1 = new System.Windows.Forms.Label();
            this.rdoAsciimode = new System.Windows.Forms.RadioButton();
            this.btnCommParam = new System.Windows.Forms.Button();
            this.rdoHexmode = new System.Windows.Forms.RadioButton();
            this.btnReadtag = new System.Windows.Forms.Button();
            this.btnRepair = new System.Windows.Forms.Button();
            this.btnWritetag = new System.Windows.Forms.Button();
            this.chkVerify = new System.Windows.Forms.CheckBox();
            this.lblStatus = new System.Windows.Forms.Label();
            this.lblStatic35 = new System.Windows.Forms.Label();
            this.btnIdcancel = new System.Windows.Forms.Button();
            this.lPort = new System.Windows.Forms.Label();
            this.bolaTagDataPanel1 = new Seagate.AAS.Parsel.Device.RFID.Hga.BolaTagDataPanel();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.label1.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.label1.Location = new System.Drawing.Point(4, 490);
            this.label1.Margin = new System.Windows.Forms.Padding(0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(655, 10);
            this.label1.TabIndex = 13;
            // 
            // rdoAsciimode
            // 
            this.rdoAsciimode.Location = new System.Drawing.Point(802, 348);
            this.rdoAsciimode.Name = "rdoAsciimode";
            this.rdoAsciimode.Size = new System.Drawing.Size(52, 17);
            this.rdoAsciimode.TabIndex = 19;
            this.rdoAsciimode.Text = "ASCII";
            this.rdoAsciimode.Visible = false;
            this.rdoAsciimode.CheckedChanged += new System.EventHandler(this.rdoAsciimode_CheckedChanged);
            // 
            // btnCommParam
            // 
            this.btnCommParam.Location = new System.Drawing.Point(760, 424);
            this.btnCommParam.Name = "btnCommParam";
            this.btnCommParam.Size = new System.Drawing.Size(129, 24);
            this.btnCommParam.TabIndex = 22;
            this.btnCommParam.Text = "Port Parameters";
            this.btnCommParam.Click += new System.EventHandler(this.btnCommParam_Click);
            // 
            // rdoHexmode
            // 
            this.rdoHexmode.Location = new System.Drawing.Point(802, 371);
            this.rdoHexmode.Name = "rdoHexmode";
            this.rdoHexmode.Size = new System.Drawing.Size(47, 17);
            this.rdoHexmode.TabIndex = 20;
            this.rdoHexmode.Text = "HEX";
            this.rdoHexmode.Visible = false;
            this.rdoHexmode.CheckedChanged += new System.EventHandler(this.rdoHexmode_CheckedChanged);
            // 
            // btnReadtag
            // 
            this.btnReadtag.Location = new System.Drawing.Point(757, 10);
            this.btnReadtag.Name = "btnReadtag";
            this.btnReadtag.Size = new System.Drawing.Size(130, 24);
            this.btnReadtag.TabIndex = 16;
            this.btnReadtag.Text = "Read Tag";
            this.btnReadtag.Click += new System.EventHandler(this.btnReadtag_Click);
            // 
            // btnRepair
            // 
            this.btnRepair.Location = new System.Drawing.Point(760, 394);
            this.btnRepair.Name = "btnRepair";
            this.btnRepair.Size = new System.Drawing.Size(129, 24);
            this.btnRepair.TabIndex = 21;
            this.btnRepair.Text = "Repair RFID Tag";
            this.btnRepair.Visible = false;
            this.btnRepair.Click += new System.EventHandler(this.btnRepair_Click);
            // 
            // btnWritetag
            // 
            this.btnWritetag.Enabled = false;
            this.btnWritetag.Location = new System.Drawing.Point(757, 37);
            this.btnWritetag.Name = "btnWritetag";
            this.btnWritetag.Size = new System.Drawing.Size(130, 24);
            this.btnWritetag.TabIndex = 17;
            this.btnWritetag.Text = "Write Tag";
            this.btnWritetag.Visible = false;
            this.btnWritetag.Click += new System.EventHandler(this.btnWritetag_Click);
            // 
            // chkVerify
            // 
            this.chkVerify.Location = new System.Drawing.Point(757, 67);
            this.chkVerify.Name = "chkVerify";
            this.chkVerify.Size = new System.Drawing.Size(139, 17);
            this.chkVerify.TabIndex = 18;
            this.chkVerify.Text = "Read After Write (Verify)";
            this.chkVerify.Visible = false;
            this.chkVerify.CheckedChanged += new System.EventHandler(this.chkVerify_CheckedChanged);
            // 
            // lblStatus
            // 
            this.lblStatus.Location = new System.Drawing.Point(49, 586);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Size = new System.Drawing.Size(474, 37);
            this.lblStatus.TabIndex = 15;
            this.lblStatus.Text = "OK";
            // 
            // lblStatic35
            // 
            this.lblStatic35.AutoSize = true;
            this.lblStatic35.Location = new System.Drawing.Point(6, 586);
            this.lblStatic35.Name = "lblStatic35";
            this.lblStatic35.Size = new System.Drawing.Size(43, 13);
            this.lblStatic35.TabIndex = 14;
            this.lblStatic35.Text = "Status :";
            // 
            // btnIdcancel
            // 
            this.btnIdcancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnIdcancel.Location = new System.Drawing.Point(760, 501);
            this.btnIdcancel.Name = "btnIdcancel";
            this.btnIdcancel.Size = new System.Drawing.Size(129, 22);
            this.btnIdcancel.TabIndex = 23;
            this.btnIdcancel.Text = "Close";
            this.btnIdcancel.Click += new System.EventHandler(this.btnIdcancel_Click);
            // 
            // lPort
            // 
            this.lPort.Location = new System.Drawing.Point(760, 451);
            this.lPort.Name = "lPort";
            this.lPort.Size = new System.Drawing.Size(127, 19);
            this.lPort.TabIndex = 25;
            this.lPort.Text = "Port :";
            this.lPort.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // bolaTagDataPanel1
            // 
            this.bolaTagDataPanel1.Location = new System.Drawing.Point(0, 12);
            this.bolaTagDataPanel1.Margin = new System.Windows.Forms.Padding(4);
            this.bolaTagDataPanel1.Name = "bolaTagDataPanel1";
            this.bolaTagDataPanel1.ReadOnly = true;
            this.bolaTagDataPanel1.Size = new System.Drawing.Size(722, 570);
            this.bolaTagDataPanel1.TabIndex = 24;
            // 
            // BolaTagDataForm
            // 
            this.ClientSize = new System.Drawing.Size(963, 632);
            this.Controls.Add(this.lPort);
            this.Controls.Add(this.bolaTagDataPanel1);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.rdoAsciimode);
            this.Controls.Add(this.btnCommParam);
            this.Controls.Add(this.rdoHexmode);
            this.Controls.Add(this.btnReadtag);
            this.Controls.Add(this.btnRepair);
            this.Controls.Add(this.btnWritetag);
            this.Controls.Add(this.chkVerify);
            this.Controls.Add(this.lblStatus);
            this.Controls.Add(this.lblStatic35);
            this.Controls.Add(this.btnIdcancel);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "BolaTagDataForm";
            this.Text = "HGA BOLA Blockless RFID Tag Reader/Writer ";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.BolaTagDataForm_FormClosed);
            this.ResumeLayout(false);
            this.PerformLayout();

        } 
		#endregion

        private Label label1;
        private RadioButton rdoAsciimode;
        private Button btnCommParam;
        private RadioButton rdoHexmode;
        private Button btnReadtag;
        private Button btnRepair;
        private Button btnWritetag;
        private CheckBox chkVerify;
        private Label lblStatus;
        private Label lblStatic35;
        private Button btnIdcancel;
        private BolaTagDataPanel bolaTagDataPanel1;
        private Label lPort;

	}
}
