//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

namespace Seagate.AAS.Parsel.Device.RFID.Hga
{
	/// <summary>
	/// Summary description for FrmCommParam.
	/// </summary>

	partial class CommParamForm : System.Windows.Forms.Form
		{
		/// <summary>
		/// Required designer variable.
		/// </summary>
        private System.ComponentModel.Container components = null;





		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if (components != null) 
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

				#region DudeLabs LLC RCConverter generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            Seagate.AAS.IO.Serial.SerialPortSettings serialPortSettings1 = new Seagate.AAS.IO.Serial.SerialPortSettings();
            this.serialPortSettingsPanel1 = new Seagate.AAS.IO.Serial.SerialPortSettingsPanel();
            this.btnOK = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // serialPortSettingsPanel1
            // 
            this.serialPortSettingsPanel1.Location = new System.Drawing.Point(2, 3);
            this.serialPortSettingsPanel1.Name = "serialPortSettingsPanel1";
            serialPortSettings1.BaudRate = 9600;
            serialPortSettings1.DataBits = 8;
            serialPortSettings1.DataMode = Seagate.AAS.IO.Serial.DataMode.Text;
            serialPortSettings1.Parity = System.IO.Ports.Parity.None;
            serialPortSettings1.PortName = "COM1";
            serialPortSettings1.StopBits = System.IO.Ports.StopBits.One;
            this.serialPortSettingsPanel1.PortSettings = serialPortSettings1;
            this.serialPortSettingsPanel1.Size = new System.Drawing.Size(170, 157);
            this.serialPortSettingsPanel1.TabIndex = 0;
            // 
            // btnOK
            // 
            this.btnOK.Location = new System.Drawing.Point(16, 166);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new System.Drawing.Size(75, 23);
            this.btnOK.TabIndex = 1;
            this.btnOK.Text = "OK";
            this.btnOK.UseVisualStyleBackColor = true;
            this.btnOK.Click += new System.EventHandler(this.btnOK_Click);
            // 
            // btnCancel
            // 
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new System.Drawing.Point(97, 166);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(75, 23);
            this.btnCancel.TabIndex = 1;
            this.btnCancel.Text = "Cancel";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // CommParamForm
            // 
            this.AcceptButton = this.btnOK;
            this.CancelButton = this.btnCancel;
            this.ClientSize = new System.Drawing.Size(189, 200);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOK);
            this.Controls.Add(this.serialPortSettingsPanel1);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "CommParamForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Communications Parameters";
            this.ResumeLayout(false);

        } 
		#endregion

        private Seagate.AAS.IO.Serial.SerialPortSettingsPanel serialPortSettingsPanel1;
        private Button btnOK;
        private Button btnCancel;

	}
}
