//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

namespace Seagate.AAS.Parsel.Device.RFID.Hga
{
	/// <summary>
	/// Summary description for HgaRfidDialogPanel.
	/// </summary>

	partial class FolaTagDataForm : System.Windows.Forms.Form
		{
		/// <summary>
		/// Required designer variable.
		/// </summary>
        private System.ComponentModel.Container components = null;





		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if (components != null) 
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

					#region DudeLabs LLC RCConverter generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.btnIdcancel = new System.Windows.Forms.Button();
            this.rdoAsciimode = new System.Windows.Forms.RadioButton();
            this.btnCommParam = new System.Windows.Forms.Button();
            this.rdoHexmode = new System.Windows.Forms.RadioButton();
            this.btnReadtag = new System.Windows.Forms.Button();
            this.btnRepair = new System.Windows.Forms.Button();
            this.btnWritetag = new System.Windows.Forms.Button();
            this.chkVerify = new System.Windows.Forms.CheckBox();
            this.lblElapsedTime = new System.Windows.Forms.Label();
            this.lblStatic35 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.lblStatus = new System.Windows.Forms.Label();
            this.chkCarrierID = new System.Windows.Forms.CheckBox();
            this.folaTagDataHgaPanel1 = new Seagate.AAS.Parsel.Device.RFID.Hga.FolaTagDataPanel();
            this.lPort = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // btnIdcancel
            // 
            this.btnIdcancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnIdcancel.Location = new System.Drawing.Point(608, 460);
            this.btnIdcancel.Name = "btnIdcancel";
            this.btnIdcancel.Size = new System.Drawing.Size(129, 22);
            this.btnIdcancel.TabIndex = 11;
            this.btnIdcancel.Text = "Close";
            // 
            // rdoAsciimode
            // 
            this.rdoAsciimode.Location = new System.Drawing.Point(616, 301);
            this.rdoAsciimode.Name = "rdoAsciimode";
            this.rdoAsciimode.Size = new System.Drawing.Size(87, 31);
            this.rdoAsciimode.TabIndex = 7;
            this.rdoAsciimode.Text = "ASCII";
            this.rdoAsciimode.Visible = false;
            this.rdoAsciimode.CheckedChanged += new System.EventHandler(this.rdoAsciimode_CheckedChanged);
            // 
            // btnCommParam
            // 
            this.btnCommParam.Location = new System.Drawing.Point(610, 391);
            this.btnCommParam.Name = "btnCommParam";
            this.btnCommParam.Size = new System.Drawing.Size(129, 24);
            this.btnCommParam.TabIndex = 10;
            this.btnCommParam.Text = "Port Parameters";
            this.btnCommParam.Click += new System.EventHandler(this.btnCommParam_Click);
            // 
            // rdoHexmode
            // 
            this.rdoHexmode.Location = new System.Drawing.Point(616, 326);
            this.rdoHexmode.Name = "rdoHexmode";
            this.rdoHexmode.Size = new System.Drawing.Size(72, 29);
            this.rdoHexmode.TabIndex = 8;
            this.rdoHexmode.Text = "HEX";
            this.rdoHexmode.Visible = false;
            this.rdoHexmode.CheckedChanged += new System.EventHandler(this.rdoHexmode_CheckedChanged);
            // 
            // btnReadtag
            // 
            this.btnReadtag.Location = new System.Drawing.Point(613, 13);
            this.btnReadtag.Name = "btnReadtag";
            this.btnReadtag.Size = new System.Drawing.Size(130, 24);
            this.btnReadtag.TabIndex = 4;
            this.btnReadtag.Text = "Read Tag";
            this.btnReadtag.Click += new System.EventHandler(this.btnReadtag_Click);
            // 
            // btnRepair
            // 
            this.btnRepair.Location = new System.Drawing.Point(610, 361);
            this.btnRepair.Name = "btnRepair";
            this.btnRepair.Size = new System.Drawing.Size(129, 24);
            this.btnRepair.TabIndex = 9;
            this.btnRepair.Text = "Repair RFID Tag";
            this.btnRepair.Visible = false;
            this.btnRepair.Click += new System.EventHandler(this.btnRepair_Click);
            // 
            // btnWritetag
            // 
            this.btnWritetag.Enabled = false;
            this.btnWritetag.Location = new System.Drawing.Point(613, 40);
            this.btnWritetag.Name = "btnWritetag";
            this.btnWritetag.Size = new System.Drawing.Size(130, 24);
            this.btnWritetag.TabIndex = 5;
            this.btnWritetag.Text = "Write Tag";
            this.btnWritetag.Visible = false;
            this.btnWritetag.Click += new System.EventHandler(this.btnWritetag_Click);
            // 
            // chkVerify
            // 
            this.chkVerify.Location = new System.Drawing.Point(616, 79);
            this.chkVerify.Name = "chkVerify";
            this.chkVerify.Size = new System.Drawing.Size(139, 29);
            this.chkVerify.TabIndex = 6;
            this.chkVerify.Text = "Read After Write (Verify)";
            this.chkVerify.Visible = false;
            this.chkVerify.CheckedChanged += new System.EventHandler(this.chkVerify_CheckedChanged);
            // 
            // lblElapsedTime
            // 
            this.lblElapsedTime.Location = new System.Drawing.Point(81, 638);
            this.lblElapsedTime.Name = "lblElapsedTime";
            this.lblElapsedTime.Size = new System.Drawing.Size(138, 14);
            this.lblElapsedTime.TabIndex = 127;
            this.lblElapsedTime.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // lblStatic35
            // 
            this.lblStatic35.AutoSize = true;
            this.lblStatic35.Location = new System.Drawing.Point(6, 570);
            this.lblStatic35.Name = "lblStatic35";
            this.lblStatic35.Size = new System.Drawing.Size(43, 13);
            this.lblStatic35.TabIndex = 2;
            this.lblStatic35.Text = "Status :";
            // 
            // label1
            // 
            this.label1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.label1.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.label1.Location = new System.Drawing.Point(3, 552);
            this.label1.Margin = new System.Windows.Forms.Padding(0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(587, 10);
            this.label1.TabIndex = 1;
            // 
            // lblStatus
            // 
            this.lblStatus.Location = new System.Drawing.Point(64, 570);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Size = new System.Drawing.Size(391, 35);
            this.lblStatus.TabIndex = 3;
            this.lblStatus.Text = "OK";
            // 
            // chkCarrierID
            // 
            this.chkCarrierID.Checked = true;
            this.chkCarrierID.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkCarrierID.Location = new System.Drawing.Point(616, 114);
            this.chkCarrierID.Name = "chkCarrierID";
            this.chkCarrierID.Size = new System.Drawing.Size(139, 46);
            this.chkCarrierID.TabIndex = 128;
            this.chkCarrierID.Text = "Check CarrierID before Write";
            // 
            // folaTagDataHgaPanel1
            // 
            this.folaTagDataHgaPanel1.Location = new System.Drawing.Point(1, 1);
            this.folaTagDataHgaPanel1.Margin = new System.Windows.Forms.Padding(4);
            this.folaTagDataHgaPanel1.Name = "folaTagDataHgaPanel1";
            this.folaTagDataHgaPanel1.ReadOnly = true;
            this.folaTagDataHgaPanel1.Size = new System.Drawing.Size(605, 528);
            this.folaTagDataHgaPanel1.TabIndex = 0;
            // 
            // lPort
            // 
            this.lPort.Location = new System.Drawing.Point(610, 418);
            this.lPort.Name = "lPort";
            this.lPort.Size = new System.Drawing.Size(127, 19);
            this.lPort.TabIndex = 129;
            this.lPort.Text = "Port :";
            this.lPort.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // FolaTagDataForm
            // 
            this.ClientSize = new System.Drawing.Size(758, 610);
            this.Controls.Add(this.lPort);
            this.Controls.Add(this.chkCarrierID);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.rdoAsciimode);
            this.Controls.Add(this.btnCommParam);
            this.Controls.Add(this.rdoHexmode);
            this.Controls.Add(this.btnReadtag);
            this.Controls.Add(this.btnRepair);
            this.Controls.Add(this.btnWritetag);
            this.Controls.Add(this.chkVerify);
            this.Controls.Add(this.lblElapsedTime);
            this.Controls.Add(this.lblStatus);
            this.Controls.Add(this.lblStatic35);
            this.Controls.Add(this.folaTagDataHgaPanel1);
            this.Controls.Add(this.btnIdcancel);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.Name = "FolaTagDataForm";
            this.Text = "HGA FOLA RFID Tag Reader/Writer";
            this.ResumeLayout(false);
            this.PerformLayout();

        } 
		#endregion

        private Button btnIdcancel;
        private Seagate.AAS.Parsel.Device.RFID.Hga.FolaTagDataPanel folaTagDataHgaPanel1;
        private RadioButton rdoAsciimode;
        private Button btnCommParam;
        private RadioButton rdoHexmode;
        private Button btnReadtag;
        private Button btnRepair;
        private Button btnWritetag;
        private CheckBox chkVerify;
        private Label lblElapsedTime;
        private Label lblStatic35;
        private Label label1;
        private Label lblStatus;
        private CheckBox chkCarrierID;
        private Label lPort;

	}
}
